# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmRCdrwFxBiQ6-GJRnmnC44X2j5Ct3G5
"""

# Step 1: Import necessary libraries
import pandas as pd
import numpy as np

# Step 2: Upload the CSV file
from google.colab import files
uploaded = files.upload()

# Load the data into a DataFrame
df = pd.read_csv(list(uploaded.keys())[0])

# Step 3: Filter Rows
# Remove rows where both column values are zero for any column pair
for col1 in df.columns:
    for col2 in df.columns:
        if col1 != col2:
            df = df[~((df[col1] == 0) & (df[col2] == 0))]

# Calculate the 95th percentile for each column
percentiles = df.quantile(0.95)

# Remove rows where any column value is greater than the 95th percentile
for col in df.columns:
    df = df[df[col] <= percentiles[col]]

# Step 4: Calculate Correlation
correlation_matrix = df.corr()

# Step 5: Display the Correlation Matrix
print("Correlation Matrix:")
print(correlation_matrix)

# Optionally, save the correlation matrix to a CSV file
correlation_matrix.to_csv('correlation_matrix.csv')

# Step 6: Download the correlation matrix file
files.download('correlation_matrix.csv')